name: themesample

environment:
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any
  rxdart: ^0.22.0

dev_dependencies:
  flutter_web_test: any
  build_runner: ^1.6.2
  build_web_compilers: ^2.0.0

dependency_overrides:
  flutter_web:
    path: ./flutter_web/packages/flutter_web
  flutter_web_test:
    path: ./flutter_web/packages/flutter_web_test
  flutter_web_ui:
    path: ./flutter_web/packages/flutter_web_ui
